MessagePrefix: true
AdminUIID: 29000
AdminUIKey: 0
GodUIID: 29001
GodUIKey: 1
VanishUIID: 29002
VanishUIKey: 2
FlyUIID: 29003
FlyUIKey: 3
CompassUIID: 29004
CompassUIKey: 4
PositionUIID: 29005
PositionUIKey: 5